// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/ssr'

const supabaseUrl = "https://sfbrnpyckebzrcjfbgwk.supabase.co"
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmYnJucHlja2VienJjamZiZ3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTExOTAsImV4cCI6MjA2NDg4NzE5MH0.zCt9i0eQ5magByfaXhiFrO-ta6CoZJjXmE0Rn4EgAkU"

export const createClient = () => {
  return createBrowserClient(supabaseUrl, supabaseAnonKey)
}

// For backward compatibility during migration
export const supabase = createClient()